spring.application.name=api_social_meli

# MySQL (compose)
spring.datasource.url=jdbc:mysql://localhost:3306/social_meli?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=user
spring.datasource.password=user123


# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG

# Mongo (compose) - com auth
spring.data.mongodb.uri=mongodb://root:root123@localhost:27017/socialmeli?authSource=admin

# Profile
spring.profiles.active=dev

# JPA
#spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG

# API
server.servlet.context-path=/api/v1